-- Creating USERS table
CREATE TABLE USERS (
   USER_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
   USERNAME VARCHAR(50),
   FIRST_NAME VARCHAR(50),
   RESTAURANT_NAME VARCHAR(50),
   LAST_NAME VARCHAR(50),
   EMAIL VARCHAR(50),
   PASSWORD INTEGER
);

-- Creating RESTAURANTS table--
CREATE TABLE RESTAURANTS (
   RESTAURANT_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
   USERNAME VARCHAR(50),
   RESTAURANT_NAME VARCHAR(50),
   EMAIL VARCHAR(50),
   RESTAURANT_OWNER VARCHAR(50),
   ADDRESS varchar(255),
   OPENING_HOURS VARCHAR(255),
   PRICE VARCHAR(10),
   COOKINGTYPE VARCHAR(50),
   CONTACT VARCHAR(50),
   MENU varchar (255),
   SPECIALDIET VARCHAR(255),
   RATING VARCHAR(255),
   PASSWORD INTEGER
);

-- Creating USER_RATES_RESTAURANT table--
CREATE TABLE USER_RATES_RESTAURANT (
   USER_ID INT,
   RESTAURANT_ID INT,
   FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID),
   FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAUTANTS (RESTAURANT_ID),
   CONSTRAINT PK_RATING PRIMARY KEY (USER_ID, RESTAURANT_ID)
);

-- Populating the tables--
--   Adding USERS--
  
INSERT INTO USERS (USERNAME, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD) VALUES ("maggie", "maggie", "simpson", "maggie@simpson.com", "1234");
INSERT INTO USERS (USERNAME, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD) VALUES ('lisa', 'lisa', 'simpson', 'lisa@simpson.com', 1509442, 0.0);
INSERT INTO USERS (USERNAME, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD) VALUES ('marge', 'marge', 'simpson', 'marge@simpson.com', 1509442, 0.0);
INSERT INTO USERS (USERNAME, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD) VALUES ('bart', 'bart', 'simpson', 'bart@simpson.com', 1509442, 0.0);
-- Adding Restaurants Users -- 
INSERT INTO USERS (USERNAME, RESTAURANT_NAME, EMAIL, PASSWORD) VALUES ("waffle1", "The Real Waffle", "waffle@gmail.com", "1234");
INSERT INTO USERS (USERNAME, RESTAURANT_NAME, EMAIL, PASSWORD) VALUES ("pizza1", "Pomodoro", "pizza@gmail.com", "1234");
INSERT INTO USERS (USERNAME, RESTAURANT_NAME, EMAIL, PASSWORD) VALUES ("meat1", "Hunter Place", "meat@gmail.com", "1234");
INSERT INTO USERS (USERNAME, RESTAURANT_NAME, EMAIL, PASSWORD) VALUES ("japanese1", "Oishii Udon", "japanese@gmail.com", "1234");
INSERT INTO USERS (USERNAME, RESTAURANT_NAME, EMAIL, PASSWORD) VALUES ("korean1", "The spicy House", "korean@gmail.com", "1234");


